-- Championship OS Supabase/PostgreSQL schema reference
-- Apply in Supabase SQL Editor only after reviewing in the target project.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  open_id text not null unique,
  name text,
  email text,
  login_method text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.tournaments (
  id bigint generated by default as identity primary key,
  name text not null,
  sport text not null,
  location text,
  start_date timestamptz,
  end_date timestamptz,
  status text not null default 'draft' check (status in ('draft','registration','live','completed')),
  ruleset text not null default 'IBJJF Standard',
  organization_name text not null default 'Championship OS',
  registration_slug text not null unique,
  weigh_in_mode text not null default 'ibjjf' check (weigh_in_mode in ('ibjjf','custom')),
  weigh_in_tolerance numeric(6,2) not null default 0,
  scale_notes text,
  created_by bigint not null references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clubs (
  id bigint generated by default as identity primary key,
  name text not null,
  country text,
  contact_name text,
  contact_phone text,
  created_at timestamptz not null default now()
);

create table if not exists public.athletes (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text,
  phone text,
  gender text not null check (gender in ('male','female')),
  belt text not null,
  expected_weight numeric(6,2) not null,
  club_id bigint references public.clubs(id),
  federation_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  name text not null,
  age_group text not null,
  gender text not null,
  belt text not null,
  weight_limit numeric(6,2) not null,
  sport text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  athlete_id bigint not null references public.athletes(id) on delete cascade,
  category_id bigint references public.categories(id),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  payment_status text not null default 'unpaid' check (payment_status in ('pending','unpaid','paid','refunded')),
  check_in_status text not null default 'not_checked_in' check (check_in_status in ('not_checked_in','checked_in')),
  weigh_in_status text not null default 'pending' check (weigh_in_status in ('pending','passed','overweight')),
  accreditation_code text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mats (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  name text not null,
  status text not null default 'idle' check (status in ('idle','active','paused')),
  created_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  category_id bigint not null references public.categories(id),
  mat_id bigint references public.mats(id),
  round text not null,
  match_number integer not null,
  athlete_a_id bigint references public.athletes(id),
  athlete_b_id bigint references public.athletes(id),
  winner_id bigint references public.athletes(id),
  score_a integer not null default 0,
  score_b integer not null default 0,
  status text not null default 'queued' check (status in ('queued','called','live','finished','no_show')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id bigint references public.users(id),
  entity_type text not null,
  entity_id bigint not null,
  action text not null,
  before_value jsonb,
  after_value jsonb,
  created_at timestamptz not null default now()
);

create index if not exists registrations_tournament_idx on public.registrations(tournament_id);
create index if not exists matches_tournament_idx on public.matches(tournament_id);
create index if not exists audit_logs_entity_idx on public.audit_logs(entity_type, entity_id);

-- Enable RLS before exposing tables through the Supabase browser client.
alter table public.users enable row level security;
alter table public.tournaments enable row level security;
alter table public.clubs enable row level security;
alter table public.athletes enable row level security;
alter table public.categories enable row level security;
alter table public.registrations enable row level security;
alter table public.mats enable row level security;
alter table public.matches enable row level security;
alter table public.audit_logs enable row level security;

-- Policies should be added only after the auth identity mapping is finalized.
-- The service-role key bypasses RLS and must stay server-side.
