import { bigint, integer, numeric, pgTable, text, timestamp, varchar } from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
  openId: text("open_id").notNull().unique(), name: text("name"), email: text("email"), loginMethod: text("login_method"), role: text("role").notNull().default("user"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(), lastSignedIn: timestamp("last_signed_in", { withTimezone: true }).notNull().defaultNow(),
});
export const tournaments = pgTable("tournaments", {
  id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(), name: text("name").notNull(), sport: text("sport").notNull(), location: text("location"), startDate: timestamp("start_date", { withTimezone: true }), endDate: timestamp("end_date", { withTimezone: true }), status: text("status").notNull().default("draft"), ruleset: text("ruleset").notNull().default("IBJJF Standard"), organizationName: text("organization_name").notNull().default("Championship OS"), registrationSlug: text("registration_slug").notNull().unique(), weighInMode: text("weigh_in_mode").notNull().default("ibjjf"), weighInTolerance: numeric("weigh_in_tolerance", { precision: 6, scale: 2 }).notNull().default("0"), scaleNotes: text("scale_notes"), createdBy: bigint("created_by", { mode: "number" }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export const clubs = pgTable("clubs", { id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(), name: text("name").notNull(), country: text("country"), contactName: text("contact_name"), contactPhone: text("contact_phone"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const athletes = pgTable("athletes", { id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(), fullName: text("full_name").notNull(), email: text("email"), phone: text("phone"), dateOfBirth: timestamp("date_of_birth", { withTimezone: true }), gender: text("gender").notNull(), belt: text("belt").notNull(), expectedWeight: numeric("expected_weight", { precision: 6, scale: 2 }), actualWeight: numeric("actual_weight", { precision: 6, scale: 2 }), clubId: bigint("club_id", { mode: "number" }), federationId: text("federation_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const categories = pgTable("categories", { id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(), tournamentId: bigint("tournament_id", { mode: "number" }).notNull(), name: text("name").notNull(), ageGroup: text("age_group").notNull(), gender: text("gender").notNull(), belt: text("belt").notNull(), weightLimit: numeric("weight_limit", { precision: 6, scale: 2 }).notNull(), sport: text("sport").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const registrations = pgTable("registrations", { id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(), tournamentId: bigint("tournament_id", { mode: "number" }).notNull(), athleteId: bigint("athlete_id", { mode: "number" }).notNull(), categoryId: bigint("category_id", { mode: "number" }), seed: integer("seed"), status: text("status").notNull().default("pending"), paymentStatus: text("payment_status").notNull().default("unpaid"), paymentMethod: text("payment_method"), checkInStatus: text("check_in_status").notNull().default("not_checked_in"), weighInStatus: text("weigh_in_status").notNull().default("pending"), weighInNotes: text("weigh_in_notes"), accreditationCode: text("accreditation_code").unique(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const mats = pgTable("mats", { id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(), tournamentId: bigint("tournament_id", { mode: "number" }).notNull(), name: text("name").notNull(), status: text("status").notNull().default("available"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const matches = pgTable("matches", { id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(), tournamentId: bigint("tournament_id", { mode: "number" }).notNull(), categoryId: bigint("category_id", { mode: "number" }).notNull(), matId: bigint("mat_id", { mode: "number" }), round: text("round").notNull(), matchNumber: integer("match_number").notNull(), athleteAId: bigint("athlete_a_id", { mode: "number" }), athleteBId: bigint("athlete_b_id", { mode: "number" }), scoreA: integer("score_a").notNull().default(0), scoreB: integer("score_b").notNull().default(0), winnerId: bigint("winner_id", { mode: "number" }), status: text("status").notNull().default("queued"), scheduledAt: timestamp("scheduled_at", { withTimezone: true }), finishedAt: timestamp("finished_at", { withTimezone: true }) });
export const auditLogs = pgTable("audit_logs", { id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(), actorUserId: bigint("actor_user_id", { mode: "number" }), entityType: text("entity_type").notNull(), entityId: bigint("entity_id", { mode: "number" }).notNull(), action: text("action").notNull(), beforeValue: text("before_value"), afterValue: text("after_value"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });

export type InsertUser = typeof users.$inferInsert;
